// <auto-generated />
using System;
using InterRapiStudy.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterRapiStudy.Migrations
{
    [DbContext(typeof(InterRapiStudyDbContext))]
    partial class InterRapiStudyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb3_general_ci")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb3");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InterRapiStudy.Models.ProgramStudy", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("program_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("ProgramId")
                        .HasName("PRIMARY");

                    b.ToTable("program_study", (string)null);
                });

            modelBuilder.Entity("InterRapiStudy.Models.ProgramSubject", b =>
                {
                    b.Property<int>("ProgSubjtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prog_subjt_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgSubjtId"));

                    b.Property<int>("ProgramId")
                        .HasColumnType("int")
                        .HasColumnName("program_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("ProgSubjtId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProgramId" }, "fk_program_detail_program1_idx");

                    b.HasIndex(new[] { "SubjectId" }, "fk_program_detail_subject1_idx");

                    b.HasIndex(new[] { "TeacherId" }, "fk_program_detail_teacher1_idx");

                    b.ToTable("program_subject", (string)null);
                });

            modelBuilder.Entity("InterRapiStudy.Models.Register", b =>
                {
                    b.Property<int>("RegId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reg_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RegId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<int>("SudentId")
                        .HasColumnType("int")
                        .HasColumnName("sudent_id");

                    b.Property<string>("Uid")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("uid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("RegId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SudentId" }, "fk_regiter_sudent1_idx");

                    b.ToTable("register", (string)null);
                });

            modelBuilder.Entity("InterRapiStudy.Models.RegisterDetail", b =>
                {
                    b.Property<int>("RegDetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reg_det_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RegDetId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<int>("ProgSublId")
                        .HasColumnType("int")
                        .HasColumnName("prog_subj_id");

                    b.Property<int>("RegiterId")
                        .HasColumnType("int")
                        .HasColumnName("regiter_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("RegDetId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProgSubjId" }, "fk_register_detail_program_detail1_idx");

                    b.HasIndex(new[] { "RegiterId" }, "fk_register_detail_regiter1_idx");

                    b.ToTable("register_detail", (string)null);
                });

            modelBuilder.Entity("InterRapiStudy.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("gender");

                    b.Property<string>("Names")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("names");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_number");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int")
                        .HasColumnName("program_id");

                    b.Property<string>("Surnames")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("surnames");

                    b.HasKey("StudentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProgramId" }, "fk_student_program1_idx");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("InterRapiStudy.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int?>("Credits")
                        .HasColumnType("int")
                        .HasColumnName("credits");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("SubjectId")
                        .HasName("PRIMARY");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("InterRapiStudy.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Email")
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("email");

                    b.Property<string>("Names")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("names");

                    b.Property<string>("Surnames")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("surnames");

                    b.HasKey("TeacherId")
                        .HasName("PRIMARY");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("InterRapiStudy.Models.ProgramSubject", b =>
                {
                    b.HasOne("InterRapiStudy.Models.ProgramStudy", "Program")
                        .WithMany("ProgramSubjects")
                        .HasForeignKey("ProgramId")
                        .IsRequired()
                        .HasConstraintName("fk_program_detail_program1");

                    b.HasOne("InterRapiStudy.Models.Subject", "Subject")
                        .WithMany("ProgramSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("fk_program_detail_subject1");

                    b.HasOne("InterRapiStudy.Models.Teacher", "Teacher")
                        .WithMany("ProgramSubjects")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("fk_program_detail_teacher1");

                    b.Navigation("Program");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("InterRapiStudy.Models.Register", b =>
                {
                    b.HasOne("InterRapiStudy.Models.Student", "Sudent")
                        .WithMany("Registers")
                        .HasForeignKey("SudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sudent");
                });

            modelBuilder.Entity("InterRapiStudy.Models.RegisterDetail", b =>
                {
                    b.HasOne("InterRapiStudy.Models.ProgramSubject", "ProgSubjl")
                        .WithMany("RegisterDetails")
                        .HasForeignKey("ProgSubjlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterRapiStudy.Models.Register", "Regiter")
                        .WithMany("RegisterDetails")
                        .HasForeignKey("RegiterId")
                        .IsRequired()
                        .HasConstraintName("fk_register_detail_regiter1");

                    b.Navigation("ProgSubjl");

                    b.Navigation("Regiter");
                });

            modelBuilder.Entity("InterRapiStudy.Models.Student", b =>
                {
                    b.HasOne("InterRapiStudy.Models.ProgramStudy", "Program")
                        .WithMany("Students")
                        .HasForeignKey("ProgramId")
                        .IsRequired()
                        .HasConstraintName("fk_student_program1");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("InterRapiStudy.Models.ProgramStudy", b =>
                {
                    b.Navigation("ProgramSubjects");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("InterRapiStudy.Models.ProgramSubject", b =>
                {
                    b.Navigation("RegisterDetails");
                });

            modelBuilder.Entity("InterRapiStudy.Models.Register", b =>
                {
                    b.Navigation("RegisterDetails");
                });

            modelBuilder.Entity("InterRapiStudy.Models.Student", b =>
                {
                    b.Navigation("Registers");
                });

            modelBuilder.Entity("InterRapiStudy.Models.Subject", b =>
                {
                    b.Navigation("ProgramSubjects");
                });

            modelBuilder.Entity("InterRapiStudy.Models.Teacher", b =>
                {
                    b.Navigation("ProgramSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
